include:
  - project: "ha-platform/control"
    ref: main
    file: "/ci/hacs-github-release.gitlab-ci.yml"

variables:
  HACS_GITHUB_REPOSITORY: "Levtos/Title_classifier"
  HACS_MANIFEST_PATH: "custom_components/title_classifier/manifest.json"
